import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import BottomNavigation from './components/BottomNavigator'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}>
        <div className="w-full bg-black p-4 fixed top-0 z-10">
          <h1 className="text-white text-lg">TrustMe</h1>
        </div>
        <main className="flex-grow flex flex-col mt-16 bg-blue-500">{children}</main>
        <BottomNavigation />
      </body>
    </html>
  )
}
